name: Publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    uses: mlm-games/ci/.github/workflows/crate-publish.yml@v1
    with:
      publish-crates-io: true
      create-release: true
      auto-bump: true
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}